### PR TITLE
Replace deprecated functions with newer ones

### PR DESCRIPTION
**Pull request by Panquesito7**
Title says it all.

### CODE REVIEW

**Comment by ObaniGemini** [comment]
We've been away from these works for years now, so thanks for your contributions. If you feel like digging the whole MinetestForFun wonky architecture, there might be some interesting things to port :)

**Comment by BetterToAutomateTheWorld** [comment]
@Panquesito7 As I see you're still doing fixes and improvements on the repository, instead of doing PR each time, would you prefer to integrate the developer team to allow you to push directly to master ? (if you want to maintain and/or update the code to allow it to run on a 5.0.0.0 server)

**Comment by Panquesito7** [comment]
> @Panquesito7 As I see you're still doing fixes and improvements on the repository, instead of doing PR each time, would you prefer to integrate the developer team to allow you to push directly to master ? (if you want to maintain and/or update the code to allow it to run on a 5.0.0.0 server)

Sure thing! Thank you, @Darcidride.
I'll update all repositories to use the newer functions.

**Comment by Panquesito7** [comment]
@Darcidride ping.

**Comment by BetterToAutomateTheWorld** [comment]
@Panquesito7 I send you an invitation as owner of the repositories, enjoy your new privileges :)

**Pull request merged**
